# lextab.py. This file automatically created by PLY (version 3.11). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('ABRE_COL', 'ABRE_PAR', 'ATE', 'ATRIBUICAO', 'DIFERENCA', 'DIVISAO', 'DOIS_PONTOS', 'ENTAO', 'ESCREVA', 'E_LOGICO', 'FECHA_COL', 'FECHA_PAR', 'FIM', 'FLUTUANTE', 'ID', 'IGUALDADE', 'INTEIRO', 'LEIA', 'MAIOR', 'MAIOR_IGUAL', 'MENOR', 'MENOR_IGUAL', 'MULTIPLICACAO', 'NEGACAO', 'NUMERO', 'NUM_FLUTUANTE', 'NUM_INTEIRO', 'NUM_NOTACAO_CIENTIFICA', 'OU_LOGICO', 'REPITA', 'RETORNA', 'SE', 'SENAO', 'SOMA', 'SUBTRACAO', 'VIRGULA'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_COMMENT>\\{[^}]*[^{]*\\})|(?P<t_NUM_NOTACAO_CIENTIFICA>[0-9]+(\\.*[0-9]*)(e(\\+|\\-| )[0-9]+))|(?P<t_NUM_FLUTUANTE>[0-9]+\\.[0-9]*)|(?P<t_NUM_INTEIRO>[0-9]+)|(?P<t_ID>[a-zA-Z_]+[a-zà-úA-ZÀ-Ú0-9_]*)|(?P<t_newline>\\n+)|(?P<t_ATRIBUICAO>\\:\\=)|(?P<t_MENOR_IGUAL>\\<\\=)|(?P<t_MAIOR_IGUAL>\\=\\>)|(?P<t_E_LOGICO>\\&\\&)|(?P<t_OU_LOGICO>\\|\\|)|(?P<t_DIFERENCA>\\<\\>)|(?P<t_SOMA>\\+)|(?P<t_MULTIPLICACAO>\\*)|(?P<t_ABRE_PAR>\\()|(?P<t_FECHA_PAR>\\))|(?P<t_IGUALDADE>\\=)|(?P<t_VIRGULA>\\,)|(?P<t_MENOR>\\<)|(?P<t_MAIOR>\\>)|(?P<t_DOIS_PONTOS>\\:)|(?P<t_ABRE_COL>\\[)|(?P<t_FECHA_COL>\\])|(?P<t_NEGACAO>\\!)|(?P<t_SUBTRACAO>-)|(?P<t_DIVISAO>/)', [None, ('t_COMMENT', 'COMMENT'), ('t_NUM_NOTACAO_CIENTIFICA', 'NUM_NOTACAO_CIENTIFICA'), None, None, None, ('t_NUM_FLUTUANTE', 'NUM_FLUTUANTE'), ('t_NUM_INTEIRO', 'NUM_INTEIRO'), ('t_ID', 'ID'), ('t_newline', 'newline'), (None, 'ATRIBUICAO'), (None, 'MENOR_IGUAL'), (None, 'MAIOR_IGUAL'), (None, 'E_LOGICO'), (None, 'OU_LOGICO'), (None, 'DIFERENCA'), (None, 'SOMA'), (None, 'MULTIPLICACAO'), (None, 'ABRE_PAR'), (None, 'FECHA_PAR'), (None, 'IGUALDADE'), (None, 'VIRGULA'), (None, 'MENOR'), (None, 'MAIOR'), (None, 'DOIS_PONTOS'), (None, 'ABRE_COL'), (None, 'FECHA_COL'), (None, 'NEGACAO'), (None, 'SUBTRACAO'), (None, 'DIVISAO')])]}
_lexstateignore = {'INITIAL': ' \t'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
